module.exports.users = [
  {
    email: 'cooperflorabarao@gmail.com',
    name: 'Organizador',
    role: 'organizer',
  },
  {
    email: 'albordignon@gmail.com',
    name: 'Organizador',
    role: 'consumer',
  },
  {
    email: 'souzasmimi@gmail.com',
    name: 'Organizador',
    role: 'consumer',
  },
  {
    email: 'luana.matallogg@gmail.com',
    name: 'Organizador',
    role: 'consumer',
  },
  {
    email: 'na.ambar@gmail.com',
    name: 'Organizador',
    role: 'consumer',
  },
  {
    email: 'gra.monteiro0@gmail.com',
    name: 'Organizador',
    role: 'consumer',
  },
  {
    email: 'viniciuscregaco@gmail.com',
    name: 'Organizador',
    role: 'consumer',
  },
  {
    email: 'mauricioesposito.eco@gmail.com',
    name: 'Organizador',
    role: 'consumer',
  },
];

module.exports.extraProducts = [
  { name: 'Abóbora', price: 4.5 },
  { name: 'Abobrinha', price: 4.5 },
  { name: 'Alface', price: 4.5 },
  { name: 'Alho poró', price: 4.5 },
  { name: 'Arroz Branco 1kg', price: 12.0 },
  { name: 'Arroz Branco 5kg', price: 36.5 },
  { name: 'Arroz Integral 1kg', price: 12.0 },
  { name: 'Açúcar mascavo 500g', price: 10.0 },
  { name: 'Banana nanica', price: 4.5 },
  { name: 'Beringela', price: 4.5 },
  { name: 'Bolinho de chuva com canela', price: 10.0 },
  { name: 'Bolacha Maisena', price: 10.0 },
  { name: 'Broa pequena de fubá', price: 10.0 },
  { name: 'Cachaça carvalho', price: 40.0 },
  { name: 'Cachaça prata', price: 40.0 },
  { name: 'Cachaça amburana', price: 40.0 },
  { name: 'Café Cecília moído', price: 18.0 },
  { name: 'Café Cecília grãos', price: 18.0 },
  { name: 'Café Terra de Sabores', price: 18.0 },
  { name: 'Chicória', price: 4.5 },
  { name: 'Cheiro Verde', price: 4.5 },
  { name: 'Coentro', price: 4.5 },
  { name: 'Couve', price: 4.5 },
  { name: 'Doce de leite em pasta', price: 12.0 },
  { name: 'Feijão 1kg', price: 15.0 },
  { name: 'Flocão de milho não transgênico', price: 7.0 },
  { name: 'Frango caipira', price: 40.0 },
  { name: 'Frango caipirão', price: 45.0 },
  { name: 'Geleia de uva', price: 13.0 },
  { name: 'Geleia de amora', price: 13.0 },
  { name: 'Mandioca com casca', price: 4.5 },
  { name: 'Mandioca sem casca', price: 6.0 },
  { name: 'Mel 300 mL', price: 13.0 },
  { name: 'Molho de tomate orgânico', price: 23.0 },
  { name: 'Nozinho de coco', price: 10.0 },
  { name: 'Pão branco', price: 10.0 },
  { name: 'Pão integral', price: 10.0 },
  { name: 'Pão de mandioca', price: 10.0 },
  { name: 'Queijo meia cura grande', price: 30.0 },
  { name: 'Queijo Fresco P', price: 15.0 },
  { name: 'Queijo Fresco G', price: 28.0 },
  { name: 'Rosca com recheio de goiabada', price: 15.0 },
  { name: 'Suco de Goiaba 1L', price: 15.0 },
  { name: 'Suco de Maçã 1L', price: 15.0 },
  { name: 'Suco de Manga 1L', price: 15.0 },
  { name: 'Suco de uva 1L', price: 15.0 },
  { name: 'Suco de Uva 1,5L', price: 18.0 },
  { name: 'Tempero Caseiro', price: 10.0 },
  { name: 'Tempero Caseiro de salsinha', price: 10.0 },
  { name: 'Tempero Caseiro de coentro', price: 10.0 },
  { name: 'Tempero Caseiro de pimenta dedo de moça', price: 10.0 },
];

